baseURL = "https://nextwave.mugee.uk/"
defaultContentLanguage = "zh-cn"
title = "后浪 NextWave"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  slogan = "信仰的后浪，青春的发声"
  description = "用文字记录成长，用声音回应信仰。"

  enableSearch = true

  author = "MUGEE"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "诗歌"
  url = "/poetry/"
  weight = 2

[[menu.main]]
  name = "散文"
  url = "/prose/"
  weight = 3

[[menu.main]]
  name = "小说"
  url = "/fiction/"
  weight = 4
[[menu.main]]
  name = "纪实"
  url = "/non-fiction/"
  weight = 5

[[menu.main]]
  name = "投稿"
  url = "/submit/"
  weight = 6

#[[menu.main]]
#  name = "搜索"
#  url = "/search/"
#  weight = 6

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
